# Generated by Django 3.0.8 on 2020-07-21 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('date', models.DateField()),
                ('media', models.CharField(default='Unknown media', max_length=100)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Height cannot be less than zero.'), django.core.validators.MaxValueValidator(100, 'Height cannot be more than 100.')])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Width cannot be less than zero.'), django.core.validators.MaxValueValidator(100, 'Width cannot be more than 100.')])),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
